### ISSUE TITLE
Missing Depencies on startup

### ISSUE THREAD

**Issue by Baraccc** [realmazharhussain/gdm-settings#82]
### What happened?

After a succefull compile, opened and said gdm ins not installed.

### Expected behavior

Just open and work as espected since all deps are installed

### To Reproduce

on debian testing,  follow the instruction to compile and run it.

### Detailed Explaination (Optional)
```
gdm-settings -v --verbosity=5
INFO: Operating System       = Debian GNU/Linux bookworm/sid
INFO: PackageType            = Unknown
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: TEMP_DIR               = /home/hamza/.cache/gdm-settings
INFO: SYSTEM_DATA_DIRS       = /usr/local/share:/usr/share
INFO: pkexec version 0.105
### Application Version
```

v0.6

### Source

source code

### Environment

- **OS**: 
- **GNOME**: 
Debian Testing
GNOME 42.3.1

**Comment by realmazharhussain** [comment]
What output does following command give?

```bash
gdm --version; echo return code: $?
```

Also, there is no need to use `--verbosity=5`. Using just `-v` is the same as using `--verbosity=5`.

**Comment by Baraccc** [comment]
> What output does following command give?
> 
> ```shell
> gdm --version; echo return code: $?
> ```
> 
> Also, there is no need to use `--verbosity=5`. Using just `-v` is the same as using `--verbosity=5`.

gdm --version; echo return code: $?
```
-bash: gdm: command not found
return code: 127
```

**Comment by realmazharhussain** [comment]
What is the output of this command?

```bash
ls /bin/*gdm*
```

**Comment by realmazharhussain** [comment]
The issue has been fixed.

**Comment by Baraccc** [comment]
its not fixed

> ```shell
> ls -1 /bin/*gdm*
> ```
ls: não foi possível acessar '/bin/*gdm*': No such file or directory

**Comment by Baraccc** [comment]
> The issue has been fixed.

nope

**Comment by realmazharhussain** [comment]
Have you tried downloading/pulling and installing the latest source code?

**Comment by sheeepdev** [comment]
Hello everyone,

It seems that the package `gdm3` (on debian unstable at least) doesnt store the binary at `/usr/bin` but rather at `/usr/sbin` and that's why gdm-settings cant find it. After copying `/usr/sbin/gdm3` both to `/usr/bin/gdm` and `/usr/bin/gdm3` gdm-settings worked without a missing dependencies prompt.

**Comment by realmazharhussain** [comment]
As you can see here

https://github.com/realmazharhussain/gdm-settings/blob/1ce22baa5a6c160f21cd3267277de9f1cf2c14b0/src/app.py#L137

The app is running the command `gdm3 --version` which should run without any problems if `/usr/sbin` is in `PATH` which it should be. And if it runs without problems, there should be no error message about missing dependencies.

So, everybody, first, **update to the latest source code** and then try compiling and running the app again.

**Comment by sheeepdev** [comment]
> As you can see here
> 
> https://github.com/realmazharhussain/gdm-settings/blob/1ce22baa5a6c160f21cd3267277de9f1cf2c14b0/src/app.py#L137
> 
> The app is running the command `gdm3 --version` which should run without any problems if `/usr/sbin` is in `PATH` which it should be. And if it runs without problems, there should be no error message about missing dependencies.
> 
> So, everybody, first, **update to the latest source code** and then try compiling and running the app again.

That is all true, but the thing is I compiled the code YESTERDAY and still had the problem. The solution I sent above only that fixed the problem!

**Comment by realmazharhussain** [comment]
OK. Thank you for clearing that for me.

**Comment by realmazharhussain** [comment]
What is the output of the following command on your system?

```bash
gdm3 --version; echo ReturnCode $?
```

**Comment by sheeepdev** [comment]
> What is the output of the following command on your system?
> 
> ```shell
> gdm3 --version; echo ReturnCode $?
> ```

Before the fix I applied the command wouldn't even work, now it returns the following:

```
GDM 42.0
ReturnCode 0
```

**Comment by realmazharhussain** [comment]
Now, I got it. I haven't used Debian in a very long time. I've just remembered that user's PATH does not include `/usr/sbin`.

I need to make sure that it is the case. Can you tell what is the output of the following commands?

```bash
echo $PATH
systemctl show-environment | grep PATH
```

**Comment by sheeepdev** [comment]
> Now, I got it. I haven't used Debian in a very long time. I've just remembered that user's PATH does not include `/usr/sbin`.
> 
> I need to make sure that it is the case. Can you tell what is the output of the following commands?
> 
> ```shell
> echo $PATH
> systemctl show-environment | grep PATH
> ```

```shell
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

systemctl show-environment | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by realmazharhussain** [comment]
From the output of `systemctl` command, it seems like `/usr/sbin` is supposed to be in PATH but something is misconfiguring PATH.

What is the output of following command?

```bash
grep '\bPATH\b' ~/.profile ~/.bash_profile /etc/profile /etc/profile.d/* ~/.bashrc /etc/bash.bashrc
```

**Comment by sheeepdev** [comment]
> From the output of `systemctl` command, it seems like `/usr/sbin` is supposed to be in PATH but something is misconfiguring PATH.
> 
> What is the output of following command?
> 
> ```shell
> grep '\bPATH\b' ~/.profile ~/.bash_profile /etc/profile /etc/profile.d/* ~/.bashrc /etc/bash.bashrc
> ```

Uhm I'm using zsh (I dont know if that means anything but yeah)

Here's the output of the command:

```shell
/home/sheep/.profile:# set PATH so it includes user's private bin if it exists
/home/sheep/.profile:    PATH="$HOME/bin:$PATH"
/home/sheep/.profile:# set PATH so it includes user's private bin if it exists
/home/sheep/.profile:    PATH="$HOME/.local/bin:$PATH"
grep: /home/sheep/.bash_profile: No such file or directory
/etc/profile:  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
/etc/profile:  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
/etc/profile:export PATH
```

**Comment by sheeepdev** [comment]
I may have found the cause!

This is line 4-9 in `/etc/profile`

```shell
if [ "$(id -u)" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH
```

**Comment by realmazharhussain** [comment]
Yes, Thank you.

In the future, the app will use a different method to check if GDM is installed or not.
